[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EMGBench"
authors = [{name = "Jehan Yang", email = "jehany@andrew.cmu.edu"}]
dynamic = ["version", "description"]
